const labels = {
  electronics: "Electronics",
  "computers-accessories": "Computers & Accessories",
  fashion: "Fashion",
  "home-kitchen": "Home & Kitchen",
  fitness: "Fitness",
  grocery: "Grocery",
  beauty: "Beauty & Personal Care",
  "books-media": "Books & Media",
  "toys-games": "Toys & Games",
  "pet-supplies": "Pet Supplies",
};

/** [id, category, price, unsplashPhotoId, name, description] */
const rows = [
  ["apple-airpods-pro-2", "electronics", "249.99", "1572569511254-d8f925fe2cbb", "Apple AirPods Pro 2", "Active noise cancellation, Adaptive Audio, USB-C charging case, and up to 6 hours of listening with ANC on."],
  ["kindle-paperwhite-16gb", "electronics", "159.99", "1544716278-ca5e3f4abd8c", "Kindle Paperwhite 16GB", "6.8-inch glare-free display, adjustable warm light, weeks of battery life, and waterproof reading for travel."],
  ["nintendo-switch-oled", "electronics", "349.99", "1578303512597-81e6cc155b3e", "Nintendo Switch OLED", "7-inch OLED screen, enhanced audio, wired LAN in the dock, and a 64GB internal storage for handheld and TV play."],
  ["ipad-air-11-m2", "electronics", "799.99", "1544244015-0df4b3ffc6b0", "iPad Air 11-inch M2", "Apple M2 chip, 11-inch Liquid Retina display, 12MP cameras, USB-C, and all-day battery for work and streaming."],
  ["sony-playstation-5", "electronics", "549.99", "1606144042614-b2417e99c4e3", "Sony PlayStation 5", "Ultra-high-speed SSD, DualSense haptic feedback, 4K gaming, and a vast library of exclusive titles."],
  ["bose-quietcomfort-earbuds", "electronics", "279.99", "1590658268037-6bf12165a8df", "Bose QuietComfort Earbuds", "World-class noise cancellation, CustomTune sound, secure fit, and up to 6 hours per charge plus the case."],
  ["canon-eos-r50", "electronics", "679.99", "1516035069371-29a1b244cc32", "Sony Alpha Mirrorless Camera", "24.2MP APS-C sensor, 4K video, fast hybrid autofocus, and a compact body for travel photography and vlogging."],
  ["samsung-galaxy-tab-s10", "electronics", "649.99", "1561154464-82e9adf32764", "Samsung Galaxy Tab S10", "Super AMOLED display, S Pen included, DeX productivity mode, and long battery life for notes and media."],
  ["anker-power-bank-20000", "electronics", "49.99", "1609091834316-d3034c0c5b0e", "Anker Power Bank 20,000mAh", "High-capacity USB-C power bank with PowerIQ fast charging for phones, tablets, and earbuds on the go."],
  ["amazon-echo-dot-5", "electronics", "59.99", "1543512214-318c7553f230", "Amazon Echo Dot (5th Gen)", "Compact smart speaker with improved audio, Alexa voice control, and a temperature sensor for routines."],
  ["logitech-mx-keys-s", "computers-accessories", "119.99", "1587829741301-dc798b83add3", "Logitech MX Keys S", "Low-profile backlit keyboard with Smart Actions, multi-device pairing, and days of charge for focused typing."],
  ["apple-magic-trackpad", "computers-accessories", "149.99", "1625948515291-696898d650d2", "Apple Magic Trackpad", "Large Force Touch surface with Multi-Touch gestures and a rechargeable battery for Mac workflows."],
  ["lg-27-ultragear-monitor", "computers-accessories", "329.99", "1527443224154-c4a3942d3acf", "LG 27\" 4K Monitor", "27-inch 4K UHD IPS display with USB-C connectivity, vibrant color accuracy, and a slim bezel design for work and entertainment."],
  ["razer-deathadder-v3", "computers-accessories", "89.99", "1615663245857-ac98b6b0b1e0", "Razer DeathAdder V3", "Ergonomic gaming mouse with Focus Pro 30K sensor, optical switches, and lightweight design."],
  ["samsung-t9-ssd-2tb", "computers-accessories", "199.99", "1591488320449-011701bb6704", "Samsung T9 Portable SSD 2TB", "USB 3.2 Gen 2x2 portable SSD with up to 2,000MB/s, shock-resistant body, and hardware encryption."],
  ["hp-laserjet-printer", "computers-accessories", "179.99", "1612815154858-991b6f0d0a0c", "HP LaserJet Wireless Printer", "Fast black-and-white laser printing, Wi-Fi, automatic duplex, and mobile print from phones."],
  ["blue-yeti-microphone", "computers-accessories", "129.99", "1590602847861-f357a9332bbc", "Blue Yeti USB Microphone", "Four pickup patterns, studio-quality recording, mute button, and headphone monitoring for streams and calls."],
  ["corsair-k70-rgb", "computers-accessories", "159.99", "1595225476474-87563907a212", "Corsair K70 RGB Keyboard", "Mechanical gaming keyboard with aluminum frame, per-key RGB, and dedicated media controls."],
  ["elgato-stream-deck-mk2", "computers-accessories", "149.99", "1616588589676-62b3bd4ff6d2", "Elgato Stream Deck MK.2", "15 LCD keys to launch apps, scenes, and shortcuts for streaming, editing, and productivity."],
  ["wacom-intuos-tablet", "computers-accessories", "99.99", "1513379733131-13f6b38b0534", "Wacom Intuos Drawing Tablet", "Pressure-sensitive pen tablet with Bluetooth, customizable ExpressKeys, and included creative software."],
  ["merino-wool-sweater", "fashion", "89.99", "1434389677669-e08b4cac3105", "Merino Wool Crew Sweater", "Soft merino knit with a classic crew neck, breathable warmth, and a clean everyday silhouette."],
  ["leather-chelsea-boots", "fashion", "159.99", "1608256246200-53e635b5b65f", "Leather Chelsea Boots", "Full-grain leather boots with elastic side panels, cushioned insole, and a durable rubber outsole."],
  ["silk-scarf-printed", "fashion", "44.99", "1601924994987-69e26d50dc26", "Printed Silk Scarf", "Lightweight 100% silk scarf with a vibrant print, rolled edges, and year-round styling versatility."],
  ["aviator-sunglasses", "fashion", "79.99", "1511499767150-a48a237f0083", "Aviator Sunglasses", "UV400 polarized lenses, metal aviator frame, adjustable nose pads, and a protective case."],
  ["canvas-tote-bag", "fashion", "29.99", "1544816155-12df9643f363", "Heavy Canvas Tote Bag", "Reinforced cotton canvas tote with interior pocket, wide straps, and enough room for a laptop."],
  ["cashmere-beanie", "fashion", "39.99", "1576871337622-98d48d3cfb7f", "Cashmere Beanie", "Soft cashmere-blend beanie with a snug rib knit and a folded cuff for cold-weather comfort."],
  ["linen-button-shirt", "fashion", "64.99", "1596755094514-f87e34085b2c", "Linen Button-Down Shirt", "Breathable linen shirt with a relaxed fit, mother-of-pearl buttons, and a slightly tailored hem."],
  ["athletic-joggers", "fashion", "49.99", "1552902865-b72c031ac5ea", "Athletic Joggers", "Stretch French terry joggers with zip pockets, tapered legs, and a drawcord waist for daily wear."],
  ["gold-hoop-earrings", "fashion", "34.99", "1535632066927-ab7c9ab60908", "Gold Hoop Earrings", "14k gold-plated hoop earrings with a lightweight hollow design and secure latch closure."],
  ["classic-trench-coat", "fashion", "189.99", "1539533018447-63fcce2678e3", "Classic Trench Coat", "Water-resistant trench with a belted waist, storm flap, and a timeless mid-length cut."],
  ["ceramic-table-lamp", "home-kitchen", "69.99", "1513506003901-1e6a229e2d15", "Ceramic Table Lamp", "Glazed ceramic base with a linen shade, in-line switch, and warm ambient light for bedside or desk."],
  ["weighted-blanket-15lb", "home-kitchen", "79.99", "1555041469-a586c61ea9bc", "Weighted Blanket 15 lb", "Evenly distributed glass-bead fill, breathable cotton cover, and a calming 15 lb weight for better sleep."],
  ["bamboo-cutting-board", "home-kitchen", "24.99", "1567375698348-5d52ce6dec60", "Bamboo Cutting Board Set", "Three nested bamboo boards with juice grooves, knife-friendly surfaces, and a hanging hole."],
  ["cast-iron-skillet-12", "home-kitchen", "54.99", "1556911220-e15b29be8c8f", "Cast Iron Skillet 12\"", "Pre-seasoned skillet that goes from stovetop to oven, with even heat and a helper handle."],
  ["essential-oil-diffuser", "home-kitchen", "32.99", "1608571423902-eed4a9abfc4d", "Essential Oil Diffuser", "Ultrasonic 300ml diffuser with color LED, auto shut-off, and whisper-quiet mist for any room."],
  ["egyptian-cotton-towels", "home-kitchen", "59.99", "1582735689369-4fe89db7114c", "Egyptian Cotton Towel Set", "Four-piece towel set in long-staple cotton with a plush pile and quick-dry weave."],
  ["standing-desk-converter", "home-kitchen", "149.99", "1593062096033-9a26b09da705", "Standing Desk Converter", "Gas-spring sit-stand riser with keyboard tray, dual monitor space, and a stable steel frame."],
  ["succulent-planter-set", "home-kitchen", "27.99", "1485955900006-10f4d324d411", "Succulent Planter Set", "Set of four ceramic planters with drainage holes, saucers, and a mix of sizes for shelves."],
  ["french-press-coffee-1l", "home-kitchen", "34.99", "1447933601403-0c6688de566e", "French Press Coffee Maker 1L", "Borosilicate glass carafe, stainless filter, and a 1-liter capacity for rich full-bodied coffee."],
  ["king-duvet-cover-set", "home-kitchen", "89.99", "1522771739844-6a9f6d5f14af", "King Duvet Cover Set", "Soft washed-cotton duvet cover with two shams, hidden zipper, and corner ties."],
  ["yoga-mat-pro-6mm", "fitness", "39.99", "1544367567-0f2fcb009e0b", "Yoga Mat Pro 6mm", "Non-slip TPE mat with 6mm cushioning, alignment markers, and a carrying strap."],
  ["resistance-bands-set", "fitness", "24.99", "1518611012118-696072aa579a", "Resistance Bands Set", "Five latex bands with door anchor, handles, and ankle straps for full-body strength work."],
  ["foam-roller-grid", "fitness", "29.99", "1571019613454-1cb2f99b2d8b", "Grid Foam Roller", "Textured foam roller for myofascial release, recovery, and pre-workout mobility."],
  ["speed-jump-rope", "fitness", "18.99", "1434682881908-74c960e617f3", "Speed Jump Rope", "Adjustable steel-cable rope with ball-bearing handles for cardio and footwork drills."],
  ["kettlebell-16kg", "fitness", "64.99", "1571019614242-c5c5dee9f50b", "Cast Iron Kettlebell 16kg", "Powder-coated kettlebell with a wide handle for swings, goblet squats, and presses."],
  ["cycling-helmet-mips", "fitness", "89.99", "1558611848-73f7eb4001a1", "Cycling Helmet with MIPS", "Lightweight ventilated helmet with MIPS protection, dial fit, and insect net."],
  ["hydration-backpack-2l", "fitness", "54.99", "1523362628745-0c100150b504", "Hydration Backpack 2L", "Trail pack with a 2L bladder, trekking-pole loops, and a breathable mesh back panel."],
  ["percussion-massage-gun", "fitness", "99.99", "1517838277536-f5f99be501cd", "Percussion Massage Gun", "Quiet brushless motor, 6 heads, 5 speeds, and a long battery for post-workout recovery."],
  ["doorway-pull-up-bar", "fitness", "34.99", "1583454110551-21d2e87d0019", "Doorway Pull-Up Bar", "No-screw doorway bar with multi-grip positions and padded contact points."],
  ["creatine-monohydrate-300g", "fitness", "29.99", "1579722820308-d74e571bf0e5", "Creatine Monohydrate 300g", "Micronized unflavored creatine with 5g servings to support strength and training volume."],
  ["organic-green-tea-100", "grocery", "14.99", "1556679343-c7306c7259e6", "Organic Green Tea 100 Bags", "Whole-leaf organic green tea in compostable bags with a clean, grassy finish."],
  ["dark-chocolate-72-bar", "grocery", "6.99", "1606312619070-d48b4c652a52", "72% Dark Chocolate Bar", "Single-origin dark chocolate with 72% cacao, low sugar, and a snap-worthy temper."],
  ["wildflower-honey-500g", "grocery", "12.99", "1587049352846-4d71b3ae608c", "Wildflower Honey 500g", "Raw unfiltered wildflower honey with a floral aroma, packed in a glass jar."],
  ["sea-salt-grinder", "grocery", "9.99", "1518112390438-7c0ce27d8e7f", "Sea Salt Grinder 200g", "Coarse sea salt in a refillable mill with an adjustable ceramic grinder."],
  ["whole-wheat-pasta-1kg", "grocery", "4.99", "1551462147-ff29053bfc14", "Whole Wheat Pasta 1kg", "Bronze-cut whole wheat spaghetti with extra fiber and a firm al dente bite."],
  ["almond-milk-1l", "grocery", "4.49", "1550583724-b2692b85b150", "Unsweetened Almond Milk 1L", "Plant milk from roasted almonds, unsweetened, shelf-stable carton for coffee and cereal."],
  ["greek-yogurt-pack", "grocery", "7.99", "1488477181052-597bdd271928", "Greek Yogurt 4-Pack", "Strained Greek yogurt with 15g protein per cup and live cultures, plain unsweetened."],
  ["granola-clusters-800g", "grocery", "9.99", "1517685352821-92cf075cc370", "Honey Granola Clusters 800g", "Oven-baked oat clusters with honey, almonds, and pumpkin seeds for breakfast bowls."],
  ["canned-chickpeas-6pack", "grocery", "8.99", "1512621776951-a57141f2eefd", "Organic Chickpeas 6-Pack", "Ready-to-use organic chickpeas in BPA-free cans for hummus, salads, and curries."],
  ["sparkling-mineral-water", "grocery", "11.99", "1548839140-29a749e1cf4d", "Sparkling Mineral Water 12-Pack", "Naturally carbonated mineral water in glass bottles with a clean, crisp finish."],
  ["hyaluronic-moisturizer", "beauty", "28.99", "1570176170700-947c9f518609", "Hyaluronic Moisturizer 50ml", "Oil-free gel cream with multi-weight hyaluronic acid for plump, hydrated skin."],
  ["spf50-mineral-sunscreen", "beauty", "24.99", "1556228578-0d85b1a4d571", "SPF 50 Mineral Sunscreen", "Broad-spectrum zinc oxide sunscreen that blends clear, water-resistant for 80 minutes."],
  ["matte-lipstick-set", "beauty", "32.99", "1586495777744-4413f21062fa", "Matte Lipstick Trio", "Three long-wear matte shades with a creamy glide and a vitamin E formula."],
  ["makeup-brush-set-12", "beauty", "29.99", "1512496015851-a90fb52ba588", "Makeup Brush Set 12-Piece", "Synthetic-bristle brushes for face and eyes, with a travel case and easy-clean fibers."],
  ["shampoo-conditioner-duo", "beauty", "26.99", "1522338140262-f46f5913618a", "Repair Shampoo & Conditioner", "Sulfate-free duo with argan oil and keratin to smooth frizz and restore shine."],
  ["beard-grooming-oil", "beauty", "18.99", "1621605815971-fbc98d665033", "Beard Grooming Oil 30ml", "Lightweight oil with jojoba and cedarwood to soften beard hair and calm skin."],
  ["nail-polish-set-6", "beauty", "22.99", "1604654894610-df63bc536371", "Nail Polish Set 6 Colors", "Chip-resistant polishes in six modern shades with a quick-dry top coat included."],
  ["gel-face-cleanser", "beauty", "16.99", "1556228720-195a672e8a03", "Gentle Gel Face Cleanser", "pH-balanced gel cleanser with ceramides and green tea that removes makeup without stripping."],
  ["cotton-sleep-mask", "beauty", "14.99", "1531353826977-0941b4779a4c", "Contoured Cotton Sleep Mask", "3D contoured mask with adjustable strap and total blackout for travel and naps."],
  ["natural-deodorant-stick", "beauty", "12.99", "1608248543803-ba4f8c1e8f3a", "Natural Deodorant Stick", "Baking-soda-free deodorant with magnesium and shea, unscented for sensitive skin."],
  ["weeknight-cookbook", "books-media", "32.99", "1495446817600-6b8091ea7b8c", "Weeknight Cookbook", "120 recipes designed for 30-minute dinners with pantry staples and full-color photos."],
  ["travel-photography-book", "books-media", "45.99", "1463320726284-311723fe7ea0", "Travel Photography Hardcover", "Large-format photo book spanning 40 countries with essays on light and place."],
  ["sci-fi-paperback-set", "books-media", "39.99", "1512820790803-83ca734da794", "Sci-Fi Paperback Box Set", "Five cult science-fiction novels in matching paperbacks with new cover art."],
  ["kids-picture-book", "books-media", "18.99", "1456513080800-7e1f5d1ab086", "Illustrated Kids Picture Book", "A bedtime story with lush illustrations, sturdy pages, and a message about kindness."],
  ["undated-weekly-planner", "books-media", "24.99", "1506784983877-45594efa4cbe", "Undated Weekly Planner", "Lay-flat planner with weekly spreads, habit trackers, and thick fountain-pen-friendly paper."],
  ["vinyl-jazz-album", "books-media", "29.99", "1511671782779-c97d3d27a1d4", "Classic Jazz Vinyl LP", "180g pressing of a landmark jazz session with restored audio and original liner notes."],
  ["gallery-art-print", "books-media", "39.99", "1579783902614-a3da3919aac8", "Gallery Art Print 50x70", "Archival giclée print on heavyweight paper, unframed, ready for a standard 50×70 cm frame."],
  ["magazine-culture-issue", "books-media", "14.99", "1504711434969-e33886168f5c", "Independent Culture Magazine", "Quarterly print magazine covering design, food, and cities with long-form features."],
  ["fountain-pen-ink-set", "books-media", "54.99", "1456327102063-fb5054efe647", "Fountain Pen & Ink Set", "Stainless steel nib fountain pen with converter, two ink bottles, and a gift box."],
  ["architecture-building-set", "toys-games", "79.99", "1587654780291-39c9404d73a0", "Architecture Building Set", "Detailed brick architecture model with 800+ pieces, display plate, and a booklet."],
  ["kids-science-kit", "toys-games", "34.99", "1503676260728-1c00da094a0b", "Kids Science Experiment Kit", "20 guided experiments with safe materials, goggles, and a full-color lab journal."],
  ["wooden-dollhouse", "toys-games", "119.99", "1515488044360-fb630310799b", "Wooden Dollhouse", "Three-story wooden house with furniture, open back for play, and non-toxic paint."],
  ["walnut-chess-set", "toys-games", "64.99", "1529692587478-5563750b4cef", "Walnut Chess Set", "Weighted wooden pieces, inlaid board, and a storage drawer for travel or home."],
  ["family-card-game", "toys-games", "19.99", "1606092195730-5d7b9af1efc5", "Family Card Game", "Fast party card game for 3–8 players, 20-minute rounds, ages 8+."],
  ["summer-water-blaster", "toys-games", "16.99", "1530541935564-ce3a8936ee25", "Summer Water Blaster", "High-capacity pump blaster with a 10-meter stream and easy-fill tank."],
  ["mini-camera-drone-kids", "toys-games", "89.99", "1473968512647-3e447244af8f", "Mini Camera Drone", "Beginner drone with altitude hold, 1080p camera, and extra propeller guards."],
  ["coloring-book-markers", "toys-games", "14.99", "1513364776144-60967b0f800f", "Coloring Book & Marker Set", "64-page coloring book plus 24 washable markers in a zip case."],
  ["stuffed-dinosaur-plush", "toys-games", "27.99", "1556015048-4d3aa10df74c", "Stuffed Dinosaur Plush", "Huggable T-rex plush with embroidered eyes and extra-soft minky fabric."],
  ["professional-yoyo", "toys-games", "21.99", "1566576912321-d58ddd7a6088", "Responsive Pro Yo-Yo", "Aluminum yo-yo with a responsive bearing, extra strings, and a starter trick guide."],
  ["covered-cat-litter-box", "pet-supplies", "42.99", "1541781774459-bb2af2f05b55", "Covered Cat Litter Box", "Hooded litter box with a carbon filter, swing door, and high sides to reduce scatter."],
  ["dog-leash-harness-set", "pet-supplies", "36.99", "1587300003388-59208cc962cb", "Dog Harness & Leash Set", "No-pull padded harness with matching 1.5m leash, reflective trim, and four sizes."],
  ["aquarium-starter-kit-20l", "pet-supplies", "79.99", "1524704654690-ba31d256c7b1", "Aquarium Starter Kit 20L", "Glass tank with LED light, filter, heater, and a setup guide for tropical fish."],
  ["wild-bird-seed-5kg", "pet-supplies", "18.99", "1444464665150-013f095f4099", "Wild Bird Seed Mix 5kg", "Sunflower, millet, and cracked corn mix for feeders, packed in a resealable bag."],
  ["pet-water-fountain-2l", "pet-supplies", "34.99", "1548199973-1c626d43e1a0", "Pet Water Fountain 2L", "Quiet circulating fountain with a replaceable filter to encourage cats and dogs to drink."],
  ["salmon-cat-treats", "pet-supplies", "8.99", "1543852786-1c2ea2f87453", "Salmon Cat Treats 150g", "Soft salmon treats with taurine, no artificial colors, and a resealable pouch."],
  ["dog-raincoat-medium", "pet-supplies", "29.99", "1450778869180-41d0601e046e", "Dog Raincoat Medium", "Waterproof shell with reflective piping, adjustable belly strap, and a leash hole."],
  ["hamster-habitat-kit", "pet-supplies", "54.99", "1425082661705-1834bfd09dca", "Hamster Habitat Kit", "Multi-level habitat with wheel, hideout, water bottle, and chew-safe platforms."],
  ["flea-comb-grooming", "pet-supplies", "11.99", "1516734212186-a967f81ad0d7", "Flea Comb Grooming Set", "Fine-tooth flea comb plus dual-sided brush for cats and small dogs."],
  ["soft-sided-pet-carrier", "pet-supplies", "49.99", "1601758228041-f3b2795255f1", "Soft-Sided Pet Carrier", "Airline-style carrier with mesh panels, padded shoulder strap, and a washable pad."],
  ["wireless-charging-pad", "electronics", "29.99", "1580910051074-3eb694886505", "15W Wireless Charging Pad", "Fast 15W Qi charger with a non-slip surface, LED indicator, and USB-C cable included."],
];

function img(photoId) {
  return `https://images.unsplash.com/${photoId.startsWith("photo-") ? photoId : `photo-${photoId}`}?w=600&h=600&fit=crop`;
}

export const extraCatalog = rows.map(([id, category, price, photoId, name, description]) => ({
  id,
  name,
  description,
  price,
  category,
  categoryLabel: labels[category],
}));

export const extraImages = Object.fromEntries(
  rows.map(([id, , , photoId]) => [id, img(photoId)])
);

const nameI18n = {
  "apple-airpods-pro-2": { fr: "Apple AirPods Pro 2", es: "Apple AirPods Pro 2", de: "Apple AirPods Pro 2", zh: "Apple AirPods Pro 2", ja: "Apple AirPods Pro 2", ko: "Apple AirPods Pro 2", hi: "Apple AirPods Pro 2", ar: "Apple AirPods Pro 2" },
  "kindle-paperwhite-16gb": { fr: "Kindle Paperwhite 16 Go", es: "Kindle Paperwhite 16 GB", de: "Kindle Paperwhite 16 GB", zh: "Kindle Paperwhite 16GB", ja: "Kindle Paperwhite 16GB", ko: "Kindle Paperwhite 16GB", hi: "Kindle Paperwhite 16GB", ar: "Kindle Paperwhite بسعة 16 جيجابايت" },
  "nintendo-switch-oled": { fr: "Nintendo Switch OLED", es: "Nintendo Switch OLED", de: "Nintendo Switch OLED", zh: "任天堂 Switch OLED", ja: "Nintendo Switch OLED", ko: "닌텐도 스위치 OLED", hi: "Nintendo Switch OLED", ar: "Nintendo Switch OLED" },
  "ipad-air-11-m2": { fr: "iPad Air 11 pouces M2", es: "iPad Air 11\" M2", de: "iPad Air 11 Zoll M2", zh: "iPad Air 11 英寸 M2", ja: "iPad Air 11インチ M2", ko: "iPad Air 11인치 M2", hi: "iPad Air 11-इंच M2", ar: "iPad Air مقاس 11 إنش M2" },
  "sony-playstation-5": { fr: "Sony PlayStation 5", es: "Sony PlayStation 5", de: "Sony PlayStation 5", zh: "索尼 PlayStation 5", ja: "Sony PlayStation 5", ko: "소니 플레이스테이션 5", hi: "Sony PlayStation 5", ar: "Sony PlayStation 5" },
  "bose-quietcomfort-earbuds": { fr: "Écouteurs Bose QuietComfort", es: "Auriculares Bose QuietComfort", de: "Bose QuietComfort Ohrhörer", zh: "Bose QuietComfort 耳机", ja: "Bose QuietComfortイヤホン", ko: "Bose QuietComfort 이어버드", hi: "Bose QuietComfort ईयरबड्स", ar: "سماعات Bose QuietComfort" },
  "canon-eos-r50": { fr: "Appareil hybride Sony Alpha", es: "Cámara mirrorless Sony Alpha", de: "Sony Alpha spiegellos", zh: "索尼 Alpha 微单相机", ja: "Sony Alpha ミラーレス", ko: "소니 알파 미러리스", hi: "Sony Alpha मिररलेस कैमरा", ar: "كاميرا سوني ألفا بدون مرآة" },
  "samsung-galaxy-tab-s10": { fr: "Samsung Galaxy Tab S10", es: "Samsung Galaxy Tab S10", de: "Samsung Galaxy Tab S10", zh: "三星 Galaxy Tab S10", ja: "Galaxy Tab S10", ko: "갤럭시 탭 S10", hi: "Samsung Galaxy Tab S10", ar: "سامسونج Galaxy Tab S10" },
  "anker-power-bank-20000": { fr: "Batterie Anker 20 000 mAh", es: "Power bank Anker 20.000 mAh", de: "Anker Powerbank 20.000 mAh", zh: "Anker 充电宝 20000mAh", ja: "Ankerモバイルバッテリー 20000mAh", ko: "Anker 보조배터리 20000mAh", hi: "Anker पावर बैंक 20,000mAh", ar: "شاحن أنكر 20000 مللي أمبير" },
  "amazon-echo-dot-5": { fr: "Amazon Echo Dot (5e gén.)", es: "Amazon Echo Dot (5.ª gen.)", de: "Amazon Echo Dot (5. Gen.)", zh: "Amazon Echo Dot（第 5 代）", ja: "Amazon Echo Dot 第5世代", ko: "아마존 에코 닷 5세대", hi: "Amazon Echo Dot (5वीं पीढ़ी)", ar: "Amazon Echo Dot الجيل الخامس" },
  "logitech-mx-keys-s": { fr: "Logitech MX Keys S", es: "Logitech MX Keys S", de: "Logitech MX Keys S", zh: "罗技 MX Keys S", ja: "ロジクール MX Keys S", ko: "로지텍 MX Keys S", hi: "Logitech MX Keys S", ar: "Logitech MX Keys S" },
  "apple-magic-trackpad": { fr: "Apple Magic Trackpad", es: "Apple Magic Trackpad", de: "Apple Magic Trackpad", zh: "Apple 妙控板", ja: "Apple Magic Trackpad", ko: "Apple Magic Trackpad", hi: "Apple Magic Trackpad", ar: "Apple Magic Trackpad" },
  "lg-27-ultragear-monitor": { fr: "Écran LG 27\" 4K", es: "Monitor LG 27\" 4K", de: "LG 27\" 4K Monitor", zh: "LG 27 英寸 4K 显示器", ja: "LG 27インチ 4Kモニター", ko: "LG 27인치 4K 모니터", hi: "LG 27\" 4K मॉनिटर", ar: "شاشة LG مقاس 27 إنش بدقة 4K" },
  "razer-deathadder-v3": { fr: "Razer DeathAdder V3", es: "Razer DeathAdder V3", de: "Razer DeathAdder V3", zh: "雷蛇 DeathAdder V3", ja: "Razer DeathAdder V3", ko: "레이저 DeathAdder V3", hi: "Razer DeathAdder V3", ar: "Razer DeathAdder V3" },
  "samsung-t9-ssd-2tb": { fr: "SSD portable Samsung T9 2 To", es: "SSD portátil Samsung T9 2 TB", de: "Samsung T9 Portable SSD 2 TB", zh: "三星 T9 移动固态硬盘 2TB", ja: "Samsung T9 ポータブルSSD 2TB", ko: "삼성 T9 포터블 SSD 2TB", hi: "Samsung T9 पोर्टेबल SSD 2TB", ar: "Samsung T9 SSD محمول 2 تيرابايت" },
  "hp-laserjet-printer": { fr: "Imprimante HP LaserJet Wi-Fi", es: "Impresora HP LaserJet Wi-Fi", de: "HP LaserJet WLAN-Drucker", zh: "惠普 LaserJet 无线打印机", ja: "HP LaserJetワイヤレスプリンター", ko: "HP LaserJet 무선 프린터", hi: "HP LaserJet वायरलेस प्रिंटर", ar: "طابعة HP LaserJet لاسلكية" },
  "blue-yeti-microphone": { fr: "Microphone USB Blue Yeti", es: "Micrófono USB Blue Yeti", de: "Blue Yeti USB-Mikrofon", zh: "Blue Yeti USB 麦克风", ja: "Blue Yeti USBマイク", ko: "Blue Yeti USB 마이크", hi: "Blue Yeti USB माइक्रोफ़ोन", ar: "ميكروفون Blue Yeti USB" },
  "corsair-k70-rgb": { fr: "Clavier Corsair K70 RGB", es: "Teclado Corsair K70 RGB", de: "Corsair K70 RGB-Tastatur", zh: "海盗船 K70 RGB 键盘", ja: "Corsair K70 RGBキーボード", ko: "커세어 K70 RGB 키보드", hi: "Corsair K70 RGB कीबोर्ड", ar: "لوحة مفاتيح Corsair K70 RGB" },
  "elgato-stream-deck-mk2": { fr: "Elgato Stream Deck MK.2", es: "Elgato Stream Deck MK.2", de: "Elgato Stream Deck MK.2", zh: "Elgato Stream Deck MK.2", ja: "Elgato Stream Deck MK.2", ko: "Elgato Stream Deck MK.2", hi: "Elgato Stream Deck MK.2", ar: "Elgato Stream Deck MK.2" },
  "wacom-intuos-tablet": { fr: "Tablette Wacom Intuos", es: "Tableta Wacom Intuos", de: "Wacom Intuos Zeichentablett", zh: "Wacom Intuos 数位板", ja: "Wacom Intuosペンタブレット", ko: "와콤 인튜어스 태블릿", hi: "Wacom Intuos ड्रॉइंग टैबलेट", ar: "لوحة رسم Wacom Intuos" },
  "merino-wool-sweater": { fr: "Pull en laine mérinos", es: "Jersey de lana merino", de: "Merinowoll-Pullover", zh: "美利奴羊毛毛衣", ja: "メリノウールセーター", ko: "메리노 울 스웨터", hi: "मेरिनो ऊन स्वेटर", ar: "كنزة صوف ميرينو" },
  "leather-chelsea-boots": { fr: "Bottines Chelsea en cuir", es: "Botines Chelsea de cuero", de: "Leder-Chelsea-Boots", zh: "皮革切尔西靴", ja: "レザーチェルシーブーツ", ko: "가죽 첼시 부츠", hi: "लेदर चेल्सी बूट्स", ar: "حذاء تشيلسي جلدي" },
  "silk-scarf-printed": { fr: "Foulard en soie imprimé", es: "Pañuelo de seda estampado", de: "Bedrucktes Seidentuch", zh: "印花真丝围巾", ja: "プリントシルクスカーフ", ko: "프린트 실크 스카프", hi: "प्रिंटेड सिल्क स्कार्फ", ar: "وشاح حرير مطبوع" },
  "aviator-sunglasses": { fr: "Lunettes aviateur", es: "Gafas de sol aviador", de: "Pilotenbrille", zh: "飞行员墨镜", ja: "アビエーターサングラス", ko: "에비에이터 선글라스", hi: "एविएटर सनग्लासेस", ar: "نظارات طيار شمسية" },
  "canvas-tote-bag": { fr: "Tote bag en toile", es: "Tote de lona", de: "Canvas-Tragetasche", zh: "厚帆布托特包", ja: "キャンバストートバッグ", ko: "캔버스 토트백", hi: "कैनवास टोट बैग", ar: "حقيبة قماش توت" },
  "cashmere-beanie": { fr: "Bonnet en cachemire", es: "Gorro de cachemira", de: "Kaschmir-Beanie", zh: "羊绒毛线帽", ja: "カシミアビーニー", ko: "캐시미어 비니", hi: "कैशमियर बीनी", ar: "قبعة كشمير" },
  "linen-button-shirt": { fr: "Chemise en lin", es: "Camisa de lino", de: "Leinenhemd", zh: "亚麻衬衫", ja: "リネンボタンシャツ", ko: "린넨 버튼 셔츠", hi: "लिनन बटन शर्ट", ar: "قميص كتان" },
  "athletic-joggers": { fr: "Jogging athlétique", es: "Joggers atléticos", de: "Athletic Joggers", zh: "运动束脚裤", ja: "アスレチックジョガー", ko: "애슬레틱 조거", hi: "एथलेटिक जॉगर्स", ar: "بنطال رياضي" },
  "gold-hoop-earrings": { fr: "Créoles dorées", es: "Aros dorados", de: "Goldene Creolen", zh: "金色圆环耳环", ja: "ゴールドフープピアス", ko: "골드 후프 귀걸이", hi: "गोल्ड हूप इयररिंग्स", ar: "أقراط حلق ذهبية" },
  "classic-trench-coat": { fr: "Trench-coat classique", es: "Gabardina clásica", de: "Klassischer Trenchcoat", zh: "经典风衣", ja: "クラシックトレンチコート", ko: "클래식 트렌치코트", hi: "क्लासिक ट्रेंच कोट", ar: "معطف ترنش كلاسيكي" },
  "ceramic-table-lamp": { fr: "Lampe de table en céramique", es: "Lámpara de mesa de cerámica", de: "Keramik-Tischlampe", zh: "陶瓷台灯", ja: "セラミックテーブルランプ", ko: "세라믹 테이블 램프", hi: "सिरेमिक टेबल लैंप", ar: "مصباح طاولة سيراميك" },
  "weighted-blanket-15lb": { fr: "Couverture lestée 7 kg", es: "Manta de peso 7 kg", de: "Gewichtsdecke 7 kg", zh: "重力毯 7kg", ja: "ウェイトブランケット 7kg", ko: "무게 담요 7kg", hi: "वेटेड ब्लैंकेट 7 किग्रा", ar: "بطانية مثقلة 7 كجم" },
  "bamboo-cutting-board": { fr: "Planches à découper bambou", es: "Tablas de cortar de bambú", de: "Bambus-Schneidebretter", zh: "竹砧板套装", ja: "バンブーまな板セット", ko: "대나무 도마 세트", hi: "बांस कटिंग बोर्ड सेट", ar: "طقم ألواح تقطيع خيزران" },
  "cast-iron-skillet-12": { fr: "Poêle en fonte 30 cm", es: "Sartén de hierro 30 cm", de: "Gusseisenpfanne 30 cm", zh: "铸铁煎锅 30cm", ja: "鋳鉄スキレット 30cm", ko: "무쇠 프라이팬 30cm", hi: "कास्ट आयरन स्किलट 30 सेमी", ar: "مقلاة حديد زهر 30 سم" },
  "essential-oil-diffuser": { fr: "Diffuseur d’huiles essentielles", es: "Difusor de aceites esenciales", de: "Ätherische-Öle-Diffusor", zh: "精油香薰机", ja: "エッセンシャルオイルディフューザー", ko: "에센셜 오일 디퓨저", hi: "एसेंशियल ऑयल डिफ्यूज़र", ar: "جهاز نشر الزيوت العطرية" },
  "egyptian-cotton-towels": { fr: "Serviettes coton égyptien", es: "Toallas de algodón egipcio", de: "Ägyptische Baumwollhandtücher", zh: "埃及棉毛巾套装", ja: "エジプト綿タオルセット", ko: "이집트산 면 타월 세트", hi: "मिस्री कॉटन तौलिया सेट", ar: "طقم مناشف قطن مصري" },
  "standing-desk-converter": { fr: "Convertisseur bureau debout", es: "Conversor de escritorio de pie", de: "Stehschreibtisch-Aufsatz", zh: "站立办公升降台", ja: "スタンディングデスクコンバーター", ko: "스탠딩 데스크 컨버터", hi: "स्टैंडिंग डेस्क कन्वर्टर", ar: "محول مكتب واقف" },
  "succulent-planter-set": { fr: "Set de pots succulentes", es: "Set de macetas suculentas", de: "Sukkulenten-Pflanztopf-Set", zh: "多肉花盆套装", ja: "多肉植物プランターセット", ko: "다육 화분 세트", hi: "सक्यूलेंट प्लांटर सेट", ar: "طقم أصص للنباتات العصارية" },
  "french-press-coffee-1l": { fr: "Cafetière à piston 1 L", es: "Prensa francesa 1 L", de: "French Press 1 L", zh: "法压壶 1L", ja: "フレンチプレス 1L", ko: "프렌치 프레스 1L", hi: "फ्रेंच प्रेस 1 लीटर", ar: "مكبس قهوة فرنسي 1 لتر" },
  "king-duvet-cover-set": { fr: "Housse de couette king", es: "Funda nórdica king", de: "King-Bettbezug-Set", zh: "加大号被套套装", ja: "キング掛け布団カバーセット", ko: "킹 이불커버 세트", hi: "किंग डुवे कवर सेट", ar: "طقم غطاء لحاف كينج" },
  "yoga-mat-pro-6mm": { fr: "Tapis de yoga Pro 6 mm", es: "Esterilla de yoga Pro 6 mm", de: "Yoga-Matte Pro 6 mm", zh: "专业瑜伽垫 6mm", ja: "ヨガマットプロ 6mm", ko: "요가 매트 프로 6mm", hi: "योगा मैट प्रो 6mm", ar: "حصيرة يوغا برو 6 مم" },
  "resistance-bands-set": { fr: "Set d’élastiques de musculation", es: "Set de bandas de resistencia", de: "Widerstandsbänder-Set", zh: "弹力带套装", ja: "レジスタンスバンドセット", ko: "저항 밴드 세트", hi: "रेज़िस्टेंस बैंड सेट", ar: "طقم أربطة مقاومة" },
  "foam-roller-grid": { fr: "Rouleau de massage grid", es: "Rodillo de foam grid", de: "Grid-Faszienrolle", zh: "网格泡沫轴", ja: "グリッドフォームローラー", ko: "그리드 폼롤러", hi: "ग्रिड फोम रोलर", ar: "أسطوانة فوم شبكية" },
  "speed-jump-rope": { fr: "Corde à sauter vitesse", es: "Cuerda de saltar rápida", de: "Speed-Springseil", zh: "竞速跳绳", ja: "スピードジャンプロープ", ko: "스피드 줄넘기", hi: "स्पीड जंप रोप", ar: "حبل قفز سريع" },
  "kettlebell-16kg": { fr: "Kettlebell fonte 16 kg", es: "Kettlebell de hierro 16 kg", de: "Gusseisen-Kettlebell 16 kg", zh: "铸铁壶铃 16kg", ja: "ケトルベル 16kg", ko: "케틀벨 16kg", hi: "केटलबेल 16 किग्रा", ar: "كيتل بل 16 كجم" },
  "cycling-helmet-mips": { fr: "Casque vélo avec MIPS", es: "Casco de ciclismo con MIPS", de: "Fahrradhelm mit MIPS", zh: "带 MIPS 的骑行头盔", ja: "MIPSサイクリングヘルメット", ko: "MIPS 자전거 헬멧", hi: "MIPS साइक्लिंग हेलमेट", ar: "خوذة دراجة مع MIPS" },
  "hydration-backpack-2l": { fr: "Sac d’hydratation 2 L", es: "Mochila de hidratación 2 L", de: "Trinkrucksack 2 L", zh: "2L 补水背包", ja: "ハイドレーションバックパック 2L", ko: "하이드레이션 백팩 2L", hi: "हाइड्रेशन बैकपैक 2L", ar: "حقيبة ترطيب 2 لتر" },
  "percussion-massage-gun": { fr: "Pistolet de massage", es: "Pistola de masaje", de: "Massagepistole", zh: "筋膜枪", ja: "マッサージガン", ko: "마사지건", hi: "मसाज गन", ar: "مسدس مساج" },
  "doorway-pull-up-bar": { fr: "Barre de traction de porte", es: "Barra de dominadas para puerta", de: "Türreck", zh: "门框引体向上杆", ja: "ドアウェイ懸垂バー", ko: "문틀 풀업바", hi: "डोरवे पुल-अप बार", ar: "عقلة باب" },
  "creatine-monohydrate-300g": { fr: "Créatine monohydrate 300 g", es: "Creatina monohidrato 300 g", de: "Kreatin-Monohydrat 300 g", zh: "一水肌酸 300g", ja: "クレアチンモノハイドレート 300g", ko: "크레아틴 모노하이드레이트 300g", hi: "क्रिएटिन मोनोहाइड्रेट 300g", ar: "كرياتين مونوهيدرات 300 جم" },
  "organic-green-tea-100": { fr: "Thé vert bio 100 sachets", es: "Té verde orgánico 100 bolsas", de: "Bio-Grüntee 100 Beutel", zh: "有机绿茶 100 袋", ja: "オーガニック緑茶 100袋", ko: "유기농 녹차 100티백", hi: "ऑर्गेनिक ग्रीन टी 100 बैग", ar: "شاي أخضر عضوي 100 كيس" },
  "dark-chocolate-72-bar": { fr: "Chocolat noir 72 %", es: "Chocolate negro 72%", de: "Zartbitterschokolade 72 %", zh: "72% 黑巧克力", ja: "ダークチョコレート 72%", ko: "다크 초콜릿 72%", hi: "डार्क चॉकलेट 72%", ar: "شوكولاتة داكنة 72٪" },
  "wildflower-honey-500g": { fr: "Miel de fleurs sauvages 500 g", es: "Miel de flores silvestres 500 g", de: "Wildblütenhonig 500 g", zh: "野花蜂蜜 500g", ja: "ワイルドフラワーハニー 500g", ko: "야생화 꿀 500g", hi: "वाइल्डफ्लावर शहद 500g", ar: "عسل أزهار برية 500 جم" },
  "sea-salt-grinder": { fr: "Moulin à sel de mer", es: "Molino de sal marina", de: "Meersalz-Mühle", zh: "海盐研磨瓶", ja: "シーソルトグラインダー", ko: "바다소금 그라인더", hi: "सी सॉल्ट ग्राइंडर", ar: "مطحنة ملح البحر" },
  "whole-wheat-pasta-1kg": { fr: "Pâtes au blé complet 1 kg", es: "Pasta integral 1 kg", de: "Vollkornpasta 1 kg", zh: "全麦意面 1kg", ja: "全粒粉パスタ 1kg", ko: "통밀 파스타 1kg", hi: "होले व्हीट पास्ता 1 किग्रा", ar: "معكرونة قمح كامل 1 كجم" },
  "almond-milk-1l": { fr: "Lait d’amande 1 L", es: "Leche de almendras 1 L", de: "Mandelmilch 1 L", zh: "杏仁奶 1L", ja: "アーモンドミルク 1L", ko: "아몬드 밀크 1L", hi: "बादाम दूध 1 लीटर", ar: "حليب لوز 1 لتر" },
  "greek-yogurt-pack": { fr: "Yaourt grec pack de 4", es: "Yogur griego pack de 4", de: "Griechischer Joghurt 4er-Pack", zh: "希腊酸奶 4 杯装", ja: "ギリシャヨーグルト 4個", ko: "그릭 요거트 4팩", hi: "ग्रीक दही 4 पैक", ar: "زبادي يوناني عبوة 4" },
  "granola-clusters-800g": { fr: "Granola croustillant 800 g", es: "Granola en clusters 800 g", de: "Granola-Clusters 800 g", zh: "蜂蜜格兰诺拉 800g", ja: "グラノーラクラスター 800g", ko: "그래놀라 클러스터 800g", hi: "ग्रैनोला क्लस्टर्स 800g", ar: "جرانولا بالعسل 800 جم" },
  "canned-chickpeas-6pack": { fr: "Pois chiches bio 6 boîtes", es: "Garbanzos orgánicos 6 latas", de: "Bio-Kichererbsen 6 Dosen", zh: "有机鹰嘴豆 6 罐", ja: "オーガニックひよこ豆 6缶", ko: "유기농 병아리콩 6캔", hi: "ऑर्गेनिक चना 6 पैक", ar: "حمص عضوي 6 علب" },
  "sparkling-mineral-water": { fr: "Eau minérale pétillante 12 bouteilles", es: "Agua mineral con gas 12 botellas", de: "Mineralwasser sprudelnd 12er", zh: "气泡矿泉水 12 瓶", ja: "炭酸ミネラルウォーター 12本", ko: "스파클링 미네랄워터 12병", hi: "स्पार्कलिंग मिनरल वॉटर 12 पैक", ar: "مياه معدنية فوارة 12 زجاجة" },
  "hyaluronic-moisturizer": { fr: "Crème acide hyaluronique 50 ml", es: "Hidratante hialurónico 50 ml", de: "Hyaluron-Feuchtigkeitscreme 50 ml", zh: "透明质酸面霜 50ml", ja: "ヒアルロン酸モイスチャライザー 50ml", ko: "히알루론산 모이스처라이저 50ml", hi: "हाइलूरोनिक मॉइस्चराइज़र 50ml", ar: "مرطب هيالورونيك 50 مل" },
  "spf50-mineral-sunscreen": { fr: "Écran solaire minéral SPF 50", es: "Protector solar mineral SPF 50", de: "Mineralisches SPF-50-Sonnenschutz", zh: "SPF50 矿物防晒", ja: "ミネラル日焼け止め SPF50", ko: "미네랄 선크림 SPF50", hi: "मिनरल सनस्क्रीन SPF 50", ar: "واقي شمس معدني SPF 50" },
  "matte-lipstick-set": { fr: "Trio de rouges à lèvres mats", es: "Trío de labiales mate", de: "Matt-Lippenstift-Trio", zh: "雾面唇膏三支装", ja: "マットリップスティック3本", ko: "매트 립스틱 트리오", hi: "मैट लिपस्टिक ट्रायो", ar: "طقم أحمر شفاه مطفي" },
  "makeup-brush-set-12": { fr: "Set de pinceaux 12 pièces", es: "Set de brochas 12 piezas", de: "Make-up-Pinsel-Set 12-teilig", zh: "化妆刷 12 件套", ja: "メイクブラシ12本セット", ko: "메이크업 브러시 12종", hi: "मेकअप ब्रश सेट 12 पीस", ar: "طقم فرش مكياج 12 قطعة" },
  "shampoo-conditioner-duo": { fr: "Duo shampoing & après-shampoing", es: "Dúo champú y acondicionador", de: "Shampoo- & Conditioner-Duo", zh: "修护洗护套装", ja: "シャンプー＆コンディショナー", ko: "샴푸 컨디셔너 듀오", hi: "शैम्पू कंडीशनर डुओ", ar: "شامبو وبلسم ثنائي" },
  "beard-grooming-oil": { fr: "Huile à barbe 30 ml", es: "Aceite para barba 30 ml", de: "Bartöl 30 ml", zh: "胡须护理油 30ml", ja: "ビアードオイル 30ml", ko: "비어드 오일 30ml", hi: "दाढ़ी का तेल 30ml", ar: "زيت اللحية 30 مل" },
  "nail-polish-set-6": { fr: "Vernis à ongles 6 couleurs", es: "Esmaltes 6 colores", de: "Nagellack-Set 6 Farben", zh: "指甲油 6 色套装", ja: "ネイルポリッシュ6色", ko: "네일 폴리시 6색", hi: "नेल पॉलिश सेट 6 रंग", ar: "طقم طلاء أظافر 6 ألوان" },
  "gel-face-cleanser": { fr: "Gel nettoyant visage", es: "Gel limpiador facial", de: "Gesichtsreinigungsgel", zh: "温和洁面凝胶", ja: "ジェル洗顔料", ko: "젤 클렌저", hi: "जेल फेस क्लेंज़र", ar: "جل منظف للوجه" },
  "cotton-sleep-mask": { fr: "Masque de sommeil coton", es: "Antifaz de algodón", de: "Baumwoll-Schlafmaske", zh: "棉质睡眠眼罩", ja: "コットンスリープマスク", ko: "코튼 수면안대", hi: "कॉटन स्लीप मास्क", ar: "قناع نوم قطني" },
  "natural-deodorant-stick": { fr: "Déodorant naturel stick", es: "Desodorante natural en barra", de: "Natürliches Deo-Stick", zh: "天然止汗膏", ja: "ナチュラルデオドラント", ko: "천연 데오드란트 스틱", hi: "नेचुरल डिओडोरेंट स्टिक", ar: "مزيل عرق طبيعي" },
  "weeknight-cookbook": { fr: "Livre de recettes en semaine", es: "Libro de cocina entre semana", de: "Alltags-Kochbuch", zh: "工作日食谱", ja: "ウィークナイトクックブック", ko: "평일 요리책", hi: "वीकनाइट कुकबुक", ar: "كتاب طبخ لأيام الأسبوع" },
  "travel-photography-book": { fr: "Livre photo voyage", es: "Libro de fotografía de viaje", de: "Reise-Fotobuch", zh: "旅行摄影画册", ja: "トラベルフォトブック", ko: "여행 사진집", hi: "ट्रैवल फोटोग्राफी बुक", ar: "كتاب تصوير السفر" },
  "sci-fi-paperback-set": { fr: "Coffret poche science-fiction", es: "Estuche de ciencia ficción", de: "Sci-Fi-Taschenbuch-Set", zh: "科幻平装套装", ja: "SFペーパーバックセット", ko: "SF 페이퍼백 세트", hi: "साइ-फाई पेपरबैक सेट", ar: "مجموعة خيال علمي ورقية" },
  "kids-picture-book": { fr: "Album illustré pour enfants", es: "Libro ilustrado infantil", de: "Kinderbilderbuch", zh: "儿童绘本", ja: "絵本", ko: "어린이 그림책", hi: "बच्चों की पिक्चर बुक", ar: "كتاب مصور للأطفال" },
  "undated-weekly-planner": { fr: "Agenda hebdomadaire non daté", es: "Agenda semanal sin fechas", de: "Undatierter Wochenplaner", zh: "无日期周计划本", ja: "日付なし週間プランナー", ko: "날짜 없는 위클리 플래너", hi: "अनडेटेड वीकली प्लानर", ar: "مخطط أسبوعي بلا تواريخ" },
  "vinyl-jazz-album": { fr: "Vinyle jazz classique", es: "Vinilo de jazz clásico", de: "Klassisches Jazz-Vinyl", zh: "经典爵士黑胶", ja: "クラシックジャズLP", ko: "클래식 재즈 바이닐", hi: "क्लासिक जैज़ विनाइल", ar: "أسطوانة جاز كلاسيكية" },
  "gallery-art-print": { fr: "Tirage d’art 50×70", es: "Lámina de arte 50×70", de: "Kunstdruck 50×70", zh: "艺术海报 50×70", ja: "アートプリント 50×70", ko: "아트 프린트 50×70", hi: "आर्ट प्रिंट 50×70", ar: "طباعة فنية 50×70" },
  "magazine-culture-issue": { fr: "Magazine culturel indépendant", es: "Revista cultural independiente", de: "Unabhängiges Kulturmagazin", zh: "独立文化杂志", ja: "インディペンデント文化誌", ko: "독립 문화 매거진", hi: "इंडिपेंडेंट कल्चर मैगज़ीन", ar: "مجلة ثقافية مستقلة" },
  "fountain-pen-ink-set": { fr: "Set stylo plume et encres", es: "Set de pluma y tintas", de: "Füllfederhalter-Set", zh: "钢笔墨水套装", ja: "万年筆インクセット", ko: "만년필 잉크 세트", hi: "फाउंटेन पेन इंक सेट", ar: "طقم قلم حبر و أحبار" },
  "architecture-building-set": { fr: "Set architecture en briques", es: "Set de arquitectura de bloques", de: "Architektur-Bauset", zh: "建筑积木套装", ja: "アーキテクチャブロックセット", ko: "건축 블록 세트", hi: "आर्किटेक्चर बिल्डिंग सेट", ar: "مجموعة بناء معمارية" },
  "kids-science-kit": { fr: "Kit sciences pour enfants", es: "Kit de ciencia para niños", de: "Kinder-Wissenschaftsset", zh: "儿童科学实验套装", ja: "キッズサイエンスキット", ko: "키즈 사이언스 키트", hi: "किड्स साइंस किट", ar: "طقم علوم للأطفال" },
  "wooden-dollhouse": { fr: "Maison de poupée en bois", es: "Casa de muñecas de madera", de: "Holz-Puppenhaus", zh: "木制娃娃屋", ja: "木製ドールハウス", ko: "원목 인형의 집", hi: "लकड़ी का डॉलहाउस", ar: "بيت دمى خشبي" },
  "walnut-chess-set": { fr: "Jeu d’échecs en noyer", es: "Ajedrez de nogal", de: "Schachspiel aus Nussbaum", zh: "胡桃木国际象棋", ja: "ウォルナットチェスセット", ko: "월넛 체스 세트", hi: "अखरोट शतरंज सेट", ar: "طقم شطرنج جوز" },
  "family-card-game": { fr: "Jeu de cartes familial", es: "Juego de cartas familiar", de: "Familien-Kartenspiel", zh: "家庭卡牌游戏", ja: "ファミリーカードゲーム", ko: "가족 카드 게임", hi: "फैमिली कार्ड गेम", ar: "لعبة ورق عائلية" },
  "summer-water-blaster": { fr: "Pistolet à eau d’été", es: "Pistola de agua de verano", de: "Sommer-Wasserpistole", zh: "夏季水枪", ja: "ウォーターブラスター", ko: "워터 블래스터", hi: "समर वॉटर ब्लास्टर", ar: "مسدس ماء صيفي" },
  "mini-camera-drone-kids": { fr: "Mini drone caméra", es: "Mini dron con cámara", de: "Mini-Kameradrohne", zh: "迷你摄像无人机", ja: "ミニカメラドローン", ko: "미니 카메라 드론", hi: "मिनी कैमरा ड्रोन", ar: "طائرة صغيرة بكاميرا" },
  "coloring-book-markers": { fr: "Cahier de coloriage et feutres", es: "Libro para colorear y rotuladores", de: "Malbuch mit Markern", zh: "涂色本与马克笔套装", ja: "塗り絵＆マーカーセット", ko: "컬러링북 마커 세트", hi: "कलरिंग बुक और मार्कर", ar: "كتاب تلوين وأقلام" },
  "stuffed-dinosaur-plush": { fr: "Peluche dinosaure", es: "Peluche dinosaurio", de: "Dino-Plüschtier", zh: "恐龙毛绒玩具", ja: "恐竜ぬいぐるみ", ko: "공룡 인형", hi: "डायनासोर प्लश", ar: "ديناصور محشو" },
  "professional-yoyo": { fr: "Yo-yo professionnel", es: "Yoyó profesional", de: "Profi-Yo-Yo", zh: "专业悠悠球", ja: "プロヨーヨー", ko: "프로 요요", hi: "प्रो यो-यो", ar: "يويو احترافي" },
  "covered-cat-litter-box": { fr: "Bac à litière couvert", es: "Arenero cubierto", de: "Abgedeckte Katzentoilette", zh: "带盖猫砂盆", ja: "カバー付き猫トイレ", ko: "커버 고양이 화장실", hi: "कवर्ड कैट लिटर बॉक्स", ar: "صندوق رمل مغلق للقطط" },
  "dog-leash-harness-set": { fr: "Harnais et laisse pour chien", es: "Arnés y correa para perro", de: "Hundegeschirr und Leine", zh: "狗胸背带与牵引绳", ja: "犬ハーネス＆リード", ko: "강아지 하네스 리드 세트", hi: "डॉग हार्नेस और लीश", ar: "طقم صدرية ومقود للكلب" },
  "aquarium-starter-kit-20l": { fr: "Kit aquarium 20 L", es: "Kit de acuario 20 L", de: "Aquarium-Starterset 20 L", zh: "水族箱入门套装 20L", ja: "アクアリウムスターター 20L", ko: "어항 스타터 키트 20L", hi: "एक्वेरियम स्टार्टर किट 20L", ar: "طقم حوض سمك 20 لتر" },
  "wild-bird-seed-5kg": { fr: "Mélange oiseaux 5 kg", es: "Mix de semillas 5 kg", de: "Wildvogelfutter 5 kg", zh: "野鸟饲料 5kg", ja: "野鳥シードミックス 5kg", ko: "야생조류 모이 5kg", hi: "वाइल्ड बर्ड सीड 5 किग्रा", ar: "بذور طيور برية 5 كجم" },
  "pet-water-fountain-2l": { fr: "Fontaine à eau 2 L", es: "Fuente de agua 2 L", de: "Trinkbrunnen 2 L", zh: "宠物饮水机 2L", ja: "ペット用給水ファウンテン 2L", ko: "펫 워터 파운틴 2L", hi: "पेट वॉटर फाउंटेन 2L", ar: "نافورة مياه للحيوانات 2 لتر" },
  "salmon-cat-treats": { fr: "Friandises chat saumon", es: "Premios de salmón para gato", de: "Lachs-Katzensnacks", zh: "三文鱼猫零食", ja: "サーモン猫トリーツ", ko: "연어 고양이 간식", hi: "सैल्मन कैट ट्रीट्स", ar: "مكافآت سلمون للقطط" },
  "dog-raincoat-medium": { fr: "Imperméable chien taille M", es: "Impermeable para perro M", de: "Hunde-Regenmantel M", zh: "中号狗雨衣", ja: "犬レインコート M", ko: "강아지 우비 M", hi: "डॉग रेनकोट मीडियम", ar: "معطف مطر للكلب مقاس M" },
  "hamster-habitat-kit": { fr: "Habitat hamster complet", es: "Hábitat para hámster", de: "Hamster-Gehege-Set", zh: "仓鼠笼套装", ja: "ハムスターハビタット", ko: "햄스터 서식지 키트", hi: "हैम्स्टर हैबिटैट किट", ar: "طقم سكن للهامستر" },
  "flea-comb-grooming": { fr: "Peigne anti-puces", es: "Peine antipulgas", de: "Flohkamm-Set", zh: "除蚤梳套装", ja: "ノミ取りコームセット", ko: "벼룩 빗 세트", hi: "फ्ली कॉम्ब सेट", ar: "طقم مشط براغيث" },
  "soft-sided-pet-carrier": { fr: "Sac de transport souple", es: "Transportín blando", de: "Weiche Transporttasche", zh: "软体宠物航空箱", ja: "ソフトペットキャリア", ko: "소프트 펫 캐리어", hi: "सॉफ्ट पेट कैरियर", ar: "حامل حيوانات ناعم" },
  "wireless-charging-pad": { fr: "Chargeur sans fil 15 W", es: "Cargador inalámbrico 15 W", de: "15-W-Induktionsladepad", zh: "15W 无线充电板", ja: "15Wワイヤレス充電パッド", ko: "15W 무선 충전 패드", hi: "15W वायरलेस चार्जिंग पैड", ar: "قاعدة شحن لاسلكي 15 واط" },
};

export const extraCopy = Object.fromEntries(
  extraCatalog.map((product) => {
    const names = nameI18n[product.id] || {};
    return [
      product.id,
      {
        en: { name: product.name, description: product.description },
        fr: { name: names.fr || product.name, description: product.description },
        es: { name: names.es || product.name, description: product.description },
        de: { name: names.de || product.name, description: product.description },
        zh: { name: names.zh || product.name, description: product.description },
        ja: { name: names.ja || product.name, description: product.description },
        ko: { name: names.ko || product.name, description: product.description },
        hi: { name: names.hi || product.name, description: product.description },
        ar: { name: names.ar || product.name, description: product.description },
      },
    ];
  })
);
