const labels = {
  "sports-outdoors": "Sports & Outdoors",
  automotive: "Automotive",
  baby: "Baby & Kids",
  office: "Office & Stationery",
  garden: "Garden & Outdoor",
  travel: "Travel & Luggage",
};

/** [id, category, price, unsplashPhotoId, name, description] */
const rows = [
  ["pro-soccer-ball", "sports-outdoors", "34.99", "1579952363873-27f3bade9f55", "Pro Match Soccer Ball", "FIFA-quality match ball with a thermally bonded surface, 32-panel design, and a hand-stitched bladder."],
  ["graphite-tennis-racket", "sports-outdoors", "129.99", "1554068865-24cecd4e34b8", "Graphite Tennis Racket", "Lightweight graphite frame, 100 sq in head, vibration-dampening grip, and a full-length cover."],
  ["camping-tent-2person", "sports-outdoors", "149.99", "1504280390367-361c6d9f38f4", "2-Person Camping Tent", "Waterproof fly, two doors, mesh ceiling, and a compact stuff sack for weekend trips."],
  ["hiking-backpack-40l", "sports-outdoors", "89.99", "1501555085422-2f70bf6dc7c0", "40L Hiking Backpack", "Ventilated harness, rain cover, hydration sleeve, and multiple pockets for day hikes."],
  ["spinning-fishing-combo", "sports-outdoors", "79.99", "1534043464128-3c43b95cdae3", "Spinning Fishing Combo", "Medium-action rod with a 5-bearing reel, spare spool, and a starter tackle pouch."],
  ["indoor-outdoor-basketball", "sports-outdoors", "29.99", "1546519638-68e109498ffc", "Indoor-Outdoor Basketball", "Composite cover that grips on hardwood and asphalt, official size 7, with a pump needle."],
  ["magnetic-car-phone-mount", "automotive", "24.99", "1486262715619-67b85e0b08d3", "Magnetic Car Phone Mount", "Strong magnet vent mount with 360° rotation, one-hand docking, and a metal plate included."],
  ["full-hd-dash-cam", "automotive", "89.99", "1449965408869-eaa3f722e40d", "Full HD Dash Cam", "1080p wide-angle camera with loop recording, G-sensor, night vision, and a 32GB card."],
  ["cordless-car-vacuum", "automotive", "49.99", "1558317374-067fb5f30001", "Cordless Car Vacuum", "Handheld 12V vacuum with crevice and brush tools, a washable filter, and a storage bag."],
  ["heavy-duty-jumper-cables", "automotive", "32.99", "1503376780353-7e6692767b70", "Heavy-Duty Jumper Cables", "4-gauge copper cables, 4-meter length, insulated clamps, and a carry pouch for emergencies."],
  ["portable-tire-inflator", "automotive", "44.99", "1486262715619-67b85e0b08d3", "Portable Tire Inflator", "Digital preset PSI, LED work light, 12V plug, and auto shut-off for cars and bikes."],
  ["backseat-car-organizer", "automotive", "22.99", "1503376780353-7e6692767b70", "Backseat Car Organizer", "Multi-pocket organizer with tablet sleeve, cup holders, and easy strap-on installation."],
  ["compact-baby-stroller", "baby", "189.99", "1522771737004-b4c2ea4c0d0e", "Compact Baby Stroller", "One-hand fold, reclining seat, sun canopy, and a reversible handle for travel and city walks."],
  ["video-baby-monitor", "baby", "99.99", "1519681393784-d120267933ba", "Video Baby Monitor", "5-inch screen, night vision, two-way talk, temperature display, and a long-range parent unit."],
  ["diaper-backpack", "baby", "54.99", "1544816155-12df9643f363", "Diaper Backpack", "Insulated bottle pockets, changing pad, USB port, and plenty of room for day-out essentials."],
  ["anti-colic-bottle-set", "baby", "29.99", "1515488044360-fb630310799b", "Anti-Colic Bottle Set", "Four BPA-free bottles with slow-flow nipples, a drying rack, and dishwasher-safe parts."],
  ["baby-activity-gym", "baby", "44.99", "1515488044360-fb630310799b", "Baby Activity Play Gym", "Soft mat with hanging toys, mirror, and removable arches for tummy time and sensory play."],
  ["toddler-high-chair", "baby", "79.99", "1515488044360-fb630310799b", "Convertible Toddler High Chair", "Adjustable tray, 5-point harness, wipe-clean seat, and a compact fold for small kitchens."],
  ["ergonomic-office-chair", "office", "219.99", "1593062096033-9a26b09da705", "Ergonomic Office Chair", "Lumbar support, breathable mesh, 4D armrests, and a smooth-rolling base for long workdays."],
  ["bamboo-desk-organizer", "office", "27.99", "1497032628192-86f99bcd76bc", "Bamboo Desk Organizer", "Multi-compartment tray for pens, notes, and devices with a warm bamboo finish."],
  ["a5-notebook-3pack", "office", "16.99", "1531346878377-a5be20888e57", "A5 Lined Notebook 3-Pack", "Dotted-grid alternative: 3 lined notebooks, 80 gsm paper, lay-flat binding, and elastic closures."],
  ["desktop-stapler-set", "office", "18.99", "1456327102063-fb5054efe647", "Desktop Stapler Set", "Full-strip stapler, 1000 staples, and a staple remover in a matching matte finish."],
  ["magnetic-whiteboard-90", "office", "64.99", "1434030216411-0b793f4b4173", "Magnetic Whiteboard 90cm", "Aluminum-frame board with markers, eraser, magnets, and wall-mount hardware."],
  ["cross-cut-shredder", "office", "79.99", "1497032628192-86f99bcd76bc", "Cross-Cut Paper Shredder", "8-sheet cross-cut shredder with a pull-out bin, jam reverse, and credit-card slot."],
  ["expandable-garden-hose", "garden", "29.99", "1416879595882-3373a0480b5b", "Expandable Garden Hose 30m", "Lightweight hose that expands under pressure, with a 9-pattern spray nozzle and storage bag."],
  ["bypass-pruning-shears", "garden", "19.99", "1416879595882-3373a0480b5b", "Bypass Pruning Shears", "SK5 steel blades, shock-absorbing grip, and a safety lock for shrubs and roses."],
  ["cedar-raised-planter", "garden", "89.99", "1416879595882-3373a0480b5b", "Cedar Raised Planter Box", "Elevated garden bed with a shelf, drainage liner, and room for herbs or salad greens."],
  ["solar-path-lights-8", "garden", "34.99", "1416879595882-3373a0480b5b", "Solar Path Lights 8-Pack", "Warm-white LED stakes that charge by day and auto-on at dusk for walkways."],
  ["galvanized-watering-can", "garden", "24.99", "1416879595882-3373a0480b5b", "Galvanized Watering Can 5L", "Classic metal can with a removable rose spout and a comfortable carry handle."],
  ["outdoor-string-lights", "garden", "39.99", "1513519245088-0ca1ef5c1c5c", "Outdoor String Lights 12m", "Weatherproof Edison-style bulbs, connectable strands, and a warm glow for patios."],
  ["hardshell-carry-on", "travel", "129.99", "1565026057447-c81acddd27b8", "Hardshell Carry-On Suitcase", "Spinner wheels, TSA lock, compression straps, and a lightweight polycarbonate shell."],
  ["packing-cubes-6set", "travel", "32.99", "1565026057447-c81acddd27b8", "Packing Cubes 6-Set", "Mesh-top cubes in mixed sizes to organize clothes, shoes, and toiletries."],
  ["memory-foam-neck-pillow", "travel", "24.99", "1436491913312-96e012612c16", "Memory Foam Neck Pillow", "Contoured pillow with a snap closure, washable cover, and compact travel pouch."],
  ["rfid-passport-holder", "travel", "19.99", "1436491913312-96e012612c16", "RFID Passport Holder", "Leather wallet for passport, cards, and tickets with RFID-blocking lining."],
  ["digital-luggage-scale", "travel", "14.99", "1565026057447-c81acddd27b8", "Digital Luggage Scale", "Backlit LCD, 50 kg capacity, tare function, and a sturdy strap for airport weigh-ins."],
  ["universal-travel-adapter", "travel", "27.99", "1580910051074-3eb694886505", "Universal Travel Adapter", "US/EU/UK/AU plugs, dual USB-A and USB-C, and a compact body for global trips."],
];

function img(photoId) {
  return `https://images.unsplash.com/photo-${photoId}?w=600&h=600&fit=crop`;
}

export const extraCatalog2 = rows.map(([id, category, price, photoId, name, description]) => ({
  id,
  name,
  description,
  price,
  category,
  categoryLabel: labels[category],
}));

export const extraImages2 = Object.fromEntries(
  rows.map(([id, , , photoId]) => [id, img(photoId)])
);

export const extraCategoryCopy = {
  "sports-outdoors": {
    en: { label: "Sports & Outdoors", blurb: "Field, trail, and weekend gear for moving outside." },
    fr: { label: "Sports & plein air", blurb: "Équipement de terrain, sentier et week-end pour bouger dehors." },
    es: { label: "Deportes y aire libre", blurb: "Equipo de campo, sendero y fin de semana para salir." },
    de: { label: "Sport & Outdoor", blurb: "Platz-, Trail- und Wochenend-Gear für draußen." },
    it: { label: "Sport e outdoor", blurb: "Attrezzatura da campo, sentiero e weekend all’aperto." },
    pt: { label: "Esportes e ar livre", blurb: "Equipamento de campo, trilha e fim de semana ao ar livre." },
    nl: { label: "Sport & outdoor", blurb: "Veld-, trail- en weekendgear voor buiten." },
    pl: { label: "Sport i outdoor", blurb: "Sprzęt na boisko, szlak i weekend na zewnątrz." },
    sv: { label: "Sport & outdoor", blurb: "Plan-, led- och helgutrustning för utomhus." },
    ar: { label: "رياضة وهواء طلق", blurb: "معدات الملعب والمسار وعطلة نهاية الأسبوع في الخارج." },
    zh: { label: "运动与户外", blurb: "球场、步道与周末户外装备。" },
    hi: { label: "स्पोर्ट्स और आउटडोर", blurb: "मैदान, ट्रेल और वीकेंड के बाहर निकलने का गियर।" },
    ja: { label: "スポーツ＆アウトドア", blurb: "フィールド、トレイル、週末の外遊びギア。" },
    ko: { label: "스포츠 & 아웃도어", blurb: "필드, 트레일, 주말 야외 장비." },
  },
  automotive: {
    en: { label: "Automotive", blurb: "In-car essentials that keep drives safer and tidier." },
    fr: { label: "Auto", blurb: "Essentiels pour la voiture, plus sûrs et plus rangés." },
    es: { label: "Automoción", blurb: "Esenciales para el coche, más seguros y ordenados." },
    de: { label: "Auto & Motorrad", blurb: "Auto-Essentials für sicherere und ordentlichere Fahrten." },
    it: { label: "Auto", blurb: "Essenziali per l’auto, più sicuri e in ordine." },
    pt: { label: "Automotivo", blurb: "Essenciais para o carro, mais seguros e organizados." },
    nl: { label: "Auto", blurb: "Auto-essentials voor veiligere, nettere ritten." },
    pl: { label: "Motoryzacja", blurb: "Niezbędniki do auta — bezpieczniej i schludniej." },
    sv: { label: "Bil", blurb: "Bilessentials för säkrare och snyggare körning." },
    ar: { label: "السيارات", blurb: "أساسيات السيارة لقيادة أكثر أمانًا وترتيبًا." },
    zh: { label: "汽车用品", blurb: "让出行更安全、更整洁的车内必备。" },
    hi: { label: "ऑटोमोटिव", blurb: "गाड़ी के ज़रूरी सामान — सुरक्षित और व्यवस्थित ड्राइव।" },
    ja: { label: "自動車用品", blurb: "ドライブを安全に、すっきり保つ車内アイテム。" },
    ko: { label: "자동차 용품", blurb: "더 안전하고 깔끔한 드라이브를 위한 차량 필수템." },
  },
  baby: {
    en: { label: "Baby & Kids", blurb: "Strollers, feeding, and play for the earliest years." },
    fr: { label: "Bébé & enfants", blurb: "Poussettes, repas et jeux pour les premières années." },
    es: { label: "Bebé e infantil", blurb: "Cochecitos, alimentación y juego para los primeros años." },
    de: { label: "Baby & Kind", blurb: "Kinderwagen, Essen und Spiel für die ersten Jahre." },
    it: { label: "Bimbo e bambini", blurb: "Passeggini, pappa e gioco per i primi anni." },
    pt: { label: "Bebê e kids", blurb: "Carrinhos, alimentação e brincar para os primeiros anos." },
    nl: { label: "Baby & kids", blurb: "Buggy's, voeding en spel voor de eerste jaren." },
    pl: { label: "Niemowlę i dzieci", blurb: "Wózki, karmienie i zabawa na pierwsze lata." },
    sv: { label: "Baby & barn", blurb: "Vagnar, mat och lek för de tidiga åren." },
    ar: { label: "الرضع والأطفال", blurb: "عربات وإطعام ولعب للسنوات الأولى." },
    zh: { label: "母婴儿童", blurb: "推车、喂养与早年玩耍用品。" },
    hi: { label: "बेबी और किड्स", blurb: "स्ट्रॉलर, फीडिंग और खेल शुरुआती सालों के लिए।" },
    ja: { label: "ベビー＆キッズ", blurb: "ベビーカー、授乳、遊び。最初の数年に。" },
    ko: { label: "베이비 & 키즈", blurb: "유모차, 수유, 놀이. 이른 해를 위해." },
  },
  office: {
    en: { label: "Office & Stationery", blurb: "Desks, chairs, and tools for getting work done." },
    fr: { label: "Bureau & papeterie", blurb: "Bureaux, chaises et outils pour avancer au travail." },
    es: { label: "Oficina y papelería", blurb: "Escritorios, sillas y herramientas para trabajar." },
    de: { label: "Büro & Schreibwaren", blurb: "Schreibtische, Stühle und Tools für den Arbeitstag." },
    it: { label: "Ufficio e cancelleria", blurb: "Scrivanie, sedie e strumenti per lavorare." },
    pt: { label: "Escritório e papelaria", blurb: "Mesas, cadeiras e ferramentas para o trabalho." },
    nl: { label: "Kantoor & papierwaren", blurb: "Bureaus, stoelen en tools om werk gedaan te krijgen." },
    pl: { label: "Biuro i papiernicze", blurb: "Biurka, krzesła i narzędzia do pracy." },
    sv: { label: "Kontor & kontorsmaterial", blurb: "Skrivbord, stolar och verktyg för jobbet." },
    ar: { label: "مكتب وقرطاسية", blurb: "مكاتب وكراسي وأدوات لإنجاز العمل." },
    zh: { label: "办公文具", blurb: "桌椅与文具，把工作做完。" },
    hi: { label: "ऑफिस और स्टेशनरी", blurb: "डेस्क, कुर्सियाँ और काम पूरा करने के औज़ार।" },
    ja: { label: "オフィス＆文具", blurb: "デスク、チェア、仕事を進めるツール。" },
    ko: { label: "오피스 & 문구", blurb: "책상, 의자, 일을 끝내는 도구." },
  },
  garden: {
    en: { label: "Garden & Outdoor", blurb: "Hose, planters, and lights for yards and balconies." },
    fr: { label: "Jardin & extérieur", blurb: "Tuyaux, jardinières et lumières pour cour et balcon." },
    es: { label: "Jardín y exterior", blurb: "Mangueras, jardineras y luces para patio y balcón." },
    de: { label: "Garten & Outdoor", blurb: "Schlauch, Pflanzkästen und Licht für Hof und Balkon." },
    it: { label: "Giardino e outdoor", blurb: "Tubi, fioriere e luci per cortile e balcone." },
    pt: { label: "Jardim e exterior", blurb: "Mangueiras, vasos e luzes para quintal e varanda." },
    nl: { label: "Tuin & buiten", blurb: "Slang, bakken en licht voor tuin en balkon." },
    pl: { label: "Ogród i taras", blurb: "Węże, donice i światło na podwórko i balkon." },
    sv: { label: "Trädgård & uteplats", blurb: "Slang, odlingslådor och ljus för gård och balkong." },
    ar: { label: "حديقة وخارج المنزل", blurb: "خراطيم وأحواض وإضاءة للفناء والشرفة." },
    zh: { label: "园艺户外", blurb: "水管、花箱与灯光，适合院子和阳台。" },
    hi: { label: "गार्डन और आउटडोर", blurb: "नली, प्लांटर और लाइट्स आँगन और बालकनी के लिए।" },
    ja: { label: "ガーデン＆アウトドア", blurb: "ホース、プランター、ライト。庭とバルコニーに。" },
    ko: { label: "가든 & 아웃도어", blurb: "호스, 플랜터, 조명. 마당과 발코니에." },
  },
  travel: {
    en: { label: "Travel & Luggage", blurb: "Bags, packing, and adapters for getting out the door." },
    fr: { label: "Voyage & bagages", blurb: "Valises, packing et adaptateurs pour partir." },
    es: { label: "Viaje y maletas", blurb: "Maletas, packing y adaptadores para salir." },
    de: { label: "Reise & Gepäck", blurb: "Koffer, Packwürfel und Adapter für unterwegs." },
    it: { label: "Viaggio e valigie", blurb: "Borse, packing e adattatori per partire." },
    pt: { label: "Viagem e bagagem", blurb: "Malas, packing e adaptadores para sair." },
    nl: { label: "Reizen & bagage", blurb: "Koffers, packing en adapters om de deur uit te gaan." },
    pl: { label: "Podróże i bagaż", blurb: "Walizki, packing i adaptery na wyjazd." },
    sv: { label: "Resa & bagage", blurb: "Väskor, packing och adaptrar för att komma iväg." },
    ar: { label: "سفر وحقائب", blurb: "حقائب وتعبئة ومحولات للانطلاق." },
    zh: { label: "旅行箱包", blurb: "行李箱、收纳与转换插头，说走就走。" },
    hi: { label: "ट्रैवल और लगेज", blurb: "बैग, पैकिंग और एडॉप्टर दरवाज़े से निकलने के लिए।" },
    ja: { label: "トラベル＆荷物", blurb: "バッグ、パッキング、アダプター。出発に。" },
    ko: { label: "여행 & 캐리어", blurb: "가방, 패킹, 어댑터. 문을 나서기 위해." },
  },
};

const nameI18n = {
  "pro-soccer-ball": { fr: "Ballon de match pro", es: "Balón de fútbol profesional", de: "Profi-Matchball", zh: "专业比赛足球", ja: "プロ試合用サッカーボール", ko: "프로 축구공", hi: "प्रो मैच फुटबॉल", ar: "كرة قدم للمباريات" },
  "graphite-tennis-racket": { fr: "Raquette tennis graphite", es: "Raqueta de tenis de grafito", de: "Graphit-Tennisschläger", zh: "石墨网球拍", ja: "グラファイトテニスラケット", ko: "그래파이트 테니스 라켓", hi: "ग्रेफाइट टेनिस रैकेट", ar: "مضرب تنس جرافيت" },
  "camping-tent-2person": { fr: "Tente 2 personnes", es: "Tienda de campaña 2 personas", de: "2-Personen-Zelt", zh: "双人露营帐篷", ja: "2人用キャンプテント", ko: "2인용 캠핑 텐트", hi: "2-व्यक्ति कैंपिंग टेंट", ar: "خيمة تخييم لشخصين" },
  "hiking-backpack-40l": { fr: "Sac de randonnée 40 L", es: "Mochila de trekking 40 L", de: "Wanderrucksack 40 L", zh: "40L 徒步背包", ja: "ハイキングバックパック 40L", ko: "하이킹 백팩 40L", hi: "हाइकिंग बैकपैक 40L", ar: "حقيبة مشي 40 لتر" },
  "spinning-fishing-combo": { fr: "Ensemble pêche spinning", es: "Combo de spinning", de: "Spinnruten-Combo", zh: "纺车轮钓具套装", ja: "スピニング釣りセット", ko: "스피닝 낚시 콤보", hi: "स्पिनिंग फिशिंग कॉम्बो", ar: "طقم صيد سبينينغ" },
  "indoor-outdoor-basketball": { fr: "Ballon de basket indoor-outdoor", es: "Balón indoor-outdoor", de: "Indoor-Outdoor-Basketball", zh: "室内外篮球", ja: "インドア＆アウトドアバスケットボール", ko: "실내외 농구공", hi: "इनडोर-आउटडोर बास्केटबॉल", ar: "كرة سلة داخلية وخارجية" },
  "magnetic-car-phone-mount": { fr: "Support téléphone magnétique", es: "Soporte magnético para coche", de: "Magnetische Handyhalterung", zh: "磁吸车载手机支架", ja: "マグネット車載ホルダー", ko: "자석 차량 거치대", hi: "मैग्नेटिक कार फोन माउंट", ar: "حامل هاتف مغناطيسي للسيارة" },
  "full-hd-dash-cam": { fr: "Caméra embarquée Full HD", es: "Cámara de salpicadero Full HD", de: "Full-HD-Dashcam", zh: "全高清行车记录仪", ja: "フルHDドライブレコーダー", ko: "풀HD 블랙박스", hi: "फुल HD डैश कैम", ar: "كاميرا سيارة Full HD" },
  "cordless-car-vacuum": { fr: "Aspirateur voiture sans fil", es: "Aspiradora de coche inalámbrica", de: "Kabelloser Auto-Staubsauger", zh: "无线车载吸尘器", ja: "コードレス車用掃除機", ko: "무선 차량용 청소기", hi: "कॉर्डलेस कार वैक्यूम", ar: "مكنسة سيارة لاسلكية" },
  "heavy-duty-jumper-cables": { fr: "Câbles de démarrage", es: "Cables de arranque", de: "Starthilfekabel", zh: "加粗搭电线", ja: "ブースターケーブル", ko: "점프 케이블", hi: "जम्पर केबल्स", ar: "كبلات تشغيل السيارة" },
  "portable-tire-inflator": { fr: "Gonfleur de pneus portable", es: "Inflador de neumáticos", de: "Tragbarer Reifenkompressor", zh: "便携轮胎充气泵", ja: "ポータブルタイヤインフレーター", ko: "휴대용 타이어 공기주입기", hi: "पोर्टेबल टायर इंफ्लेटर", ar: "منفاخ إطارات محمول" },
  "backseat-car-organizer": { fr: "Organiseur siège arrière", es: "Organizador de asiento trasero", de: "Rücksitz-Organizer", zh: "后座收纳袋", ja: "後部座席オーガナイザー", ko: "뒷좌석 정리함", hi: "बैकसीट कार ऑर्गनाइज़र", ar: "منظم المقعد الخلفي" },
  "compact-baby-stroller": { fr: "Poussette compacte", es: "Cochecito compacto", de: "Kompakter Kinderwagen", zh: "轻便婴儿推车", ja: "コンパクトベビーカー", ko: "컴팩트 유모차", hi: "कॉम्पैक्ट बेबी स्ट्रॉलर", ar: "عربة أطفال مدمجة" },
  "video-baby-monitor": { fr: "Babyphone vidéo", es: "Vigilabebés con vídeo", de: "Video-Babyphone", zh: "视频婴儿监视器", ja: "ビデオベビーモニター", ko: "비디오 아기 모니터", hi: "वीडियो बेबी मॉनिटर", ar: "جهاز مراقبة الطفل بالفيديو" },
  "diaper-backpack": { fr: "Sac à langer sac à dos", es: "Mochila cambiador", de: "Wickelrucksack", zh: "妈咪包双肩", ja: "マザーズリュック", ko: "기저귀 백팩", hi: "डायपर बैकपैक", ar: "حقيبة حفاضات ظهرية" },
  "anti-colic-bottle-set": { fr: "Set biberons anti-coliques", es: "Set de biberones anticólicos", de: "Anti-Kolik-Flaschen-Set", zh: "防胀气奶瓶套装", ja: "アンチコリック哺乳瓶セット", ko: "배앓이 방지 젖병 세트", hi: "एंटी-कॉलिक बोतल सेट", ar: "طقم زجاجات ضد المغص" },
  "baby-activity-gym": { fr: "Tapis d’éveil bébé", es: "Gimnasio de actividades", de: "Baby-Spielbogen", zh: "婴儿健身架", ja: "ベビージム", ko: "아기 액티비티 짐", hi: "बेबी एक्टिविटी जिम", ar: "سجادة أنشطة للرضع" },
  "toddler-high-chair": { fr: "Chaise haute évolutive", es: "Trona convertible", de: "Mitwachsender Hochstuhl", zh: "儿童餐椅", ja: "ベビーハイチェア", ko: "유아 하이체어", hi: "टॉडलर हाई चेयर", ar: "كرسي طعام للأطفال" },
  "ergonomic-office-chair": { fr: "Chaise de bureau ergonomique", es: "Silla de oficina ergonómica", de: "Ergonomischer Bürostuhl", zh: "人体工学办公椅", ja: "エルゴノミックオフィスチェア", ko: "인체공학 사무용 의자", hi: "एर्गोनॉमिक ऑफिस चेयर", ar: "كرسي مكتب مريح" },
  "bamboo-desk-organizer": { fr: "Organiseur de bureau bambou", es: "Organizador de escritorio de bambú", de: "Bambus-Schreibtisch-Organizer", zh: "竹制桌面收纳", ja: "バンブーデスクオーガナイザー", ko: "대나무 책상 정리함", hi: "बांस डेस्क ऑर्गनाइज़र", ar: "منظم مكتب خيزران" },
  "a5-notebook-3pack": { fr: "Carnets A5 lot de 3", es: "Cuadernos A5 pack de 3", de: "A5-Notizbücher 3er-Pack", zh: "A5 笔记本 3 本装", ja: "A5ノート 3冊", ko: "A5 노트 3팩", hi: "A5 नोटबुक 3 पैक", ar: "دفاتر A5 عبوة 3" },
  "desktop-stapler-set": { fr: "Set agrafeuse de bureau", es: "Set de grapadora de escritorio", de: "Tischhefter-Set", zh: "桌面订书机套装", ja: "卓上ホッチキスセット", ko: "데스크 스테이플러 세트", hi: "डेस्कटॉप स्टेपलर सेट", ar: "طقم دباسة مكتب" },
  "magnetic-whiteboard-90": { fr: "Tableau blanc magnétique 90 cm", es: "Pizarra magnética 90 cm", de: "Magnetisches Whiteboard 90 cm", zh: "磁性白板 90cm", ja: "マグネットホワイトボード 90cm", ko: "자석 화이트보드 90cm", hi: "मैग्नेटिक व्हाइटबोर्ड 90 सेमी", ar: "سبورة بيضاء مغناطيسية 90 سم" },
  "cross-cut-shredder": { fr: "Destructeur de documents", es: "Destructora de papel", de: "Aktenvernichter Kreuzschnitt", zh: "碎纸机", ja: "クロスカットシュレッダー", ko: "문서세단기", hi: "क्रॉस-कट श्रेडर", ar: "آلة تقطيع ورق" },
  "expandable-garden-hose": { fr: "Tuyau de jardin extensible 30 m", es: "Manguera expandible 30 m", de: "Dehnbarer Gartenschlauch 30 m", zh: "伸缩花园水管 30m", ja: "伸縮ガーデンホース 30m", ko: "확장 정원 호스 30m", hi: "एक्सपेंडेबल गार्डन होज़ 30m", ar: "خرطوم حديقة قابل للتمدد 30 م" },
  "bypass-pruning-shears": { fr: "Sécateur bypass", es: "Tijeras de podar", de: "Bypass-Gartenschere", zh: "修枝剪", ja: "剪定ばさみ", ko: "전정가위", hi: "प्रूनिंग शियर्स", ar: "مقص تقليم" },
  "cedar-raised-planter": { fr: "Jardinière surélevée cèdre", es: "Jardinera elevada de cedro", de: "Zeder-Hochbeet", zh: "雪松高架种植箱", ja: "シダーレイズドプランター", ko: "시더 화단 박스", hi: "सीडर रेज़्ड प्लांटर", ar: "حوض زراعة مرتفع من الأرز" },
  "solar-path-lights-8": { fr: "Bornes solaires lot de 8", es: "Luces solares pack de 8", de: "Solar-Wegeleuchten 8er", zh: "太阳能路灯 8 件", ja: "ソーラーパスライト 8本", ko: "태양광 길조명 8개", hi: "सोलर पाथ लाइट्स 8 पैक", ar: "أضواء ممر شمسية 8 قطع" },
  "galvanized-watering-can": { fr: "Arrosoir galvanisé 5 L", es: "Regadera galvanizada 5 L", de: "Verzinkte Gießkanne 5 L", zh: "镀锌洒水壶 5L", ja: "トタンジョーロ 5L", ko: "아연 물뿌리개 5L", hi: "गैल्वनाइज्ड वॉटरिंग कैन 5L", ar: "إبريق سقي مجلفن 5 لتر" },
  "outdoor-string-lights": { fr: "Guirlande lumineuse 12 m", es: "Guirnalda de luces 12 m", de: "Lichterkette 12 m", zh: "户外灯串 12m", ja: "屋外ストリングライト 12m", ko: "야외 스트링 라이트 12m", hi: "आउटडोर स्ट्रिंग लाइट्स 12m", ar: "إضاءة خيط خارجية 12 م" },
  "hardshell-carry-on": { fr: "Valise cabine coque dure", es: "Maleta de cabina rígida", de: "Hartschalen-Handgepäck", zh: "硬壳登机箱", ja: "ハードシェル機内持ち込み", ko: "하드쉘 기내용 캐리어", hi: "हार्डशेल कैरी-ऑन", ar: "حقيبة مقصورة صلبة" },
  "packing-cubes-6set": { fr: "Cubes de rangement lot de 6", es: "Cubos de packing pack de 6", de: "Packwürfel 6er-Set", zh: "旅行收纳袋 6 件", ja: "パッキングキューブ 6点", ko: "패킹 큐브 6세트", hi: "पैकिंग क्यूब्स 6 सेट", ar: "مكعبات تعبئة 6 قطع" },
  "memory-foam-neck-pillow": { fr: "Coussin de voyage mémoire de forme", es: "Almohada de viaje viscoelástica", de: "Nackenkissen Memory-Foam", zh: "记忆棉颈枕", ja: "ネックピロー メモリーフォーム", ko: "메모리폼 목베개", hi: "मेमोरी फोम नेक पिलो", ar: "وسادة رقبة فوم الذاكرة" },
  "rfid-passport-holder": { fr: "Porte-passeport RFID", es: "Portapasaporte RFID", de: "RFID-Reisepasshülle", zh: "RFID 护照夹", ja: "RFIDパスポートホルダー", ko: "RFID 여권 홀더", hi: "RFID पासपोर्ट होल्डर", ar: "حافظة جواز RFID" },
  "digital-luggage-scale": { fr: "Pèse-bagage digital", es: "Báscula de maleta digital", de: "Digitale Kofferwaage", zh: "电子行李秤", ja: "デジタル荷物スケール", ko: "디지털 여행가방 저울", hi: "डिजिटल लगेज स्केल", ar: "ميزان حقائب رقمي" },
  "universal-travel-adapter": { fr: "Adaptateur de voyage universel", es: "Adaptador de viaje universal", de: "Universal-Reiseadapter", zh: "全球旅行转换插头", ja: "ユニバーサルトラベルアダプター", ko: "유니버설 여행 어댑터", hi: "यूनिवर्सल ट्रैवल एडॉप्टर", ar: "محول سفر عالمي" },
};

export const extraCopy2 = Object.fromEntries(
  extraCatalog2.map((product) => {
    const names = nameI18n[product.id] || {};
    return [
      product.id,
      {
        en: { name: product.name, description: product.description },
        fr: { name: names.fr || product.name, description: product.description },
        es: { name: names.es || product.name, description: product.description },
        de: { name: names.de || product.name, description: product.description },
        zh: { name: names.zh || product.name, description: product.description },
        ja: { name: names.ja || product.name, description: product.description },
        ko: { name: names.ko || product.name, description: product.description },
        hi: { name: names.hi || product.name, description: product.description },
        ar: { name: names.ar || product.name, description: product.description },
      },
    ];
  })
);
