apiVersion: v1
kind: Service
metadata:
  name: nuvio-service
  namespace: nuvio
  labels:
    app: nuvio
spec:
  type: ClusterIP
  selector:
    app: nuvio
  ports:
    - name: http
      port: 80
      targetPort: 8080
